### ISSUE TITLE
Prepare for user testing

### ISSUE THREAD

**Issue by kprzerwa** [CERNDocumentServer/cds-ils#151]
- [x] Check all the workflows
  - Literature request
    - [x] Create a literature request, authors do not appear for it page displayed in the backoffice
    - [x] Cancel a literature request
    - [x] Select/Remove Document
  - Circulation
    - [x] loan request
    - [x] cancel loan request, patron and librarian
    - [x] create loan
    - [x] cancel loan
    - [x] full loan cycle
    - [x] loan extension request
  - Acquisition
    - [x] Select/Remove existing order
  - ILL
    - [x] Create new Borrowing request
  - Updates
    - [x] Frontsite Patron's `Your Loans Page` counters update properly
    - [x] Frontsite literature details page, updates when gets on loan
    - [x] Backoffice Loans `Filter By` counters update properly

- [x] Change the setup script to optionally avoid the creation of any demo data
- [x] CERN vocabularies and values #125
- [x] Static pages content #106
- [x] Review the configuration variables #80
  - emails should be sent only to one specific email address. Decided with the library, to be applied in the environment.
- [x] Review ES mappings: do they have the same fields as the schemas? Are the resolved $ref fields added to the mappings?
- [x] Test migration data for user testing

**Comment by FlorianCassayre** [comment]
ES mappings manual review:
- [ ] Acquisition
- [ ] Circulation loan (`invenio-circulation`)
- [ ] Document request
- [ ] Document
- [ ] E-item
- [ ] ILL borrowing request
- [ ] ILL library
- [ ] Internal location
- [ ] Item
- [ ] Location
- [ ] Patron
- [ ] Series
- [ ] Stats aggregation file download
- [ ] Stats file download
- [ ] Vocabulary

**Comment by ntarocco** [comment]
Only missing to complete the emails changes and content.
