### ISSUE TITLE
Migration - EPIC

### ISSUE THREAD

**Issue by kprzerwa** [CERNDocumentServer/cds-ils#152]
- [ ] Ingesting both cases of the multiparts (for now only one works)
- [ ] Testing the loan migration scripts
- [ ] Cleaning the migrator-kit
- [ ] Files migration scripts
- [ ] Corner cases: Yellow reports etc
- [ ] Relations matching script
- [ ] Cleaning data by the Library
- [ ] Testing everything in many cycles
