### ISSUE TITLE
Migration - EPIC

### ISSUE THREAD

**Issue by kprzerwa** [CERNDocumentServer/cds-ils#153]
- [x] Ingesting both cases of the multiparts (for now only one works)
- [x] Testing the loan migration scripts
- [x] Cleaning the migrator-kit
- [x] Files migration scripts
- [x] Corner cases: Yellow reports etc
- [x] Relations matching script
- [ ] Cleaning data by the Library
- [ ] Testing everything in many cycles
