### ISSUE TITLE
importer: preview of changes

### ISSUE THREAD

**Issue by kprzerwa** [CERNDocumentServer/cds-ils#321]
Implement a preview of the changes which are about to be done via importer.

The preview should be visible after uploading an XML file, but before performing any changes in the DB. The Librarian should be able to choose if they want to continue the import based on the preview.

In the minimal implementation it could be json preview, similar to what was done for cds-migrator-kit.
At the moment, in CDS, librarians can see the converted/mapped XMLs that are about to be imported in a textarea and can check each value.

## Tasks

- [ ] Implement the preview: this should be the first mandatory step. The outcome could be simply the JSON output that will be imported:
```
r = Record(dict(...data...))
json.dump(r)
```
The extra complexity is when creating e.g. eitem/item which require an imported document, a created PID. Can we fake such PID and put e.g. `document_pid:<newly imported PID>`?
- [ ] After the preview, the button `Import` will appear
- [ ] Change the table of results after import to be able to support the display of more of 1K results for a single job. The easiest is to simply show a very simple table, probably with pagination or infinite scrolling (how does the webpage react to 1K elements?)
