### ISSUE TITLE
Importer/syncer EPIC

### ISSUE THREAD

**Issue by kprzerwa** [CERNDocumentServer/cds-ils#49]
Analyse what needs to be done to implement an importer of books. No UI implementation, focus on the the logic and backend.
- [Library input](https://docs.google.com/document/d/1KUgnuSkqhZ2V7jT9zaF-joI6FlB_Hfyyx9Jet25_19M/edit#heading=h.momkif13bi25)
- [Books Project requirements](https://codimd.web.cern.ch/0p-ZhZDnTAycgWGNULBXBQ#UC)

[Draft requirements & questions](https://codimd.web.cern.ch/Y_BJxtFRT86TVXKeXXYPVQ?both)

[Providers](https://docs.google.com/spreadsheets/d/1wTtwt85EilEfa5B25yFAprxK5_LCxuEQtscTCzmx0y8/edit#gid=40753147)

**Comment by topless** [comment]
# Importer tasks

> NOTE: this is a draft proposal feel free to improve or redesign accordingly,
> `source` is what is referred as `provider`

We need to build a tool that will accomplish the following:

## Configuration

* [ ] CLI/UI to trigger different/all combinations of sources -> destination.
* [ ] Configurable `sources` where we will get the `e-items`. It is required
for every `source` to have:
  * [ ] a `title`
  * [ ] a `rank` (order of sources is important),
  * [ ] an `API` url.
* [ ] Configurable `destination` where we will store the `e-items`. CDS-ILS is
the `destination` for our case. For `destination` is required to configure:
  * [ ] endpoint to search for `e-items`
  * [ ] endpoint to search for `documents`
  * [ ] endpoint to post `e-item`
* [ ] Configurable conditions, each condition should be matched with an action.
  * [ ] `e-item` does not exist in `destination`
  * [ ] `document` for `e-item` does not exist in `destination`
  * [ ] `e-item` exists in `destination`, coming from same `source`
  * [ ] `e-item` exists in `destination`, coming from different `source`
* [ ] Configurable actions
  * [ ] create `document`
  * [ ] create `e-item`
  * [ ] attach `e-item` to `document`
  * [ ] update existing `e-item`

## Bussiness logic

> NOTE: an `e-item` should fullfill only **ONE** condition, maybe we should
> evaluate all conditions and if it fullfills more than one, flag the `e-item`

Compose the aforementiond configurations to accommodate the following cases

* [ ] if the `e-item` does not exist in `destination`, search for `document`
and create it if it does not exist. Then create a new `e-item` and attach it
to the `document`.
* [ ] if `e-item` exists in `destination` but not in `source`, then flag it
for manual removal from the libarian.
* [ ] if `e-item` exists in `destination` and is coming from same `source`
attach it to the relevant `document`.
* [ ] if `e-item` exists in `destiation` and is coming from different `source`
replace the attached item to the `document` with the new one.

## Usage

* [ ] Fetch list of `e-items` from a `source`.
* [ ] Parse necessary MarcXML `e-item` information.
* [ ] Iterate `conditions` on `e-item`.
* [ ] Apply `action` according to matching `condition`.
* [ ] Log `source`, `e-item`, `condition`, `action`.
